"""Data audit for data/sms.tsv. Writes results/audit.md and returns the numbers."""

import os

from common import DATA_PATH, RESULTS_DIR, label_conflicts, load_data, normalize


def run_audit(path=DATA_PATH):
    with open(path, encoding="utf-8") as f:
        raw_lines = sum(1 for _ in f)

    df = load_data(path)
    legacy = load_data(path, legacy_parsing=True)

    unique = df["message"].nunique()
    empty = int(df["message"].fillna("").str.strip().eq("").sum())

    lengths = df["message"].str.len()
    length_stats = {
        label: {
            "n": int(group.size),
            "mean": round(float(group.mean()), 1),
            "median": float(group.median()),
            "min": int(group.min()),
            "max": int(group.max()),
        }
        for label, group in lengths.groupby(df["label"])
    }

    # Near-duplicates: distinct exact messages that collapse together after normalizing.
    exact = df.drop_duplicates(subset="message")
    norm = exact["message"].map(normalize)
    near_dup_extra = int(len(exact) - norm.nunique())
    near_dup_groups = int((norm.value_counts() > 1).sum())
    near_dup_label_conflicts = int((exact.groupby(norm)["label"].nunique() > 1).sum())

    audit = {
        "raw_lines": raw_lines,
        "rows": int(len(df)),
        "legacy_parser_rows": int(len(legacy)),
        "legacy_parser_altered_messages": int((~legacy["message"].isin(set(df["message"]))).sum()),
        "unique_messages": int(unique),
        "exact_duplicate_rows": int(len(df) - unique),
        "label_conflicts": len(label_conflicts(df)),
        "empty_or_whitespace_messages": empty,
        "spam_rows": int((df["label"] == "spam").sum()),
        "spam_share": round(float((df["label"] == "spam").mean()), 4),
        "spam_share_after_dedupe": round(float((exact["label"] == "spam").mean()), 4),
        "near_duplicate_extra_messages": near_dup_extra,
        "near_duplicate_groups": near_dup_groups,
        "near_duplicate_label_conflicts": near_dup_label_conflicts,
        "length_chars_by_class": length_stats,
    }
    write_audit_md(audit)
    return audit


def write_audit_md(a):
    lines = [
        "# Data audit: data/sms.tsv",
        "",
        "Generated by `audit.py`. Do not edit by hand.",
        "",
        "| Check | Value |",
        "|---|---|",
        f"| Lines in the raw file | {a['raw_lines']} |",
        f"| Rows read (no quote parsing) | {a['rows']} |",
        f"| Rows read by the pandas default parser (v1) | {a['legacy_parser_rows']} |",
        f"| Messages the default parser changed or merged | {a['legacy_parser_altered_messages']} |",
        f"| Unique messages | {a['unique_messages']} |",
        f"| Exact duplicate rows | {a['exact_duplicate_rows']} |",
        f"| Label conflicts (same text, different labels) | {a['label_conflicts']} |",
        f"| Empty or whitespace-only messages | {a['empty_or_whitespace_messages']} |",
        f"| Spam rows | {a['spam_rows']} |",
        f"| Spam share (all rows) | {a['spam_share']:.2%} |",
        f"| Spam share (after dropping exact duplicates) | {a['spam_share_after_dedupe']:.2%} |",
        f"| Near-duplicate groups (match after lowercasing, trimming, removing punctuation) | {a['near_duplicate_groups']} |",
        f"| Extra messages inside those groups (flagged, not dropped) | {a['near_duplicate_extra_messages']} |",
        f"| Near-duplicate groups with conflicting labels | {a['near_duplicate_label_conflicts']} |",
        "",
        "## Message length in characters, by class",
        "",
        "| Class | n | Mean | Median | Min | Max |",
        "|---|---|---|---|---|---|",
    ]
    for label, s in a["length_chars_by_class"].items():
        lines.append(f"| {label} | {s['n']} | {s['mean']} | {s['median']} | {s['min']} | {s['max']} |")
    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(os.path.join(RESULTS_DIR, "audit.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    for key, value in run_audit().items():
        print(f"{key}: {value}")
