"""Reproduce everything: audit, evaluation, casebook, and the README results table."""

import re

from audit import run_audit
from evaluate import comparison_table, fmt, holdout_table, run_evaluation

README = "README.md"
START, END = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"


def results_block(m):
    a = m["audit"]
    o = m["original_split_seen_vs_unseen"]
    return "\n".join([
        START,
        "<!-- Generated by run_all.py from results/metrics.json. Do not edit by hand. -->",
        "",
        "**v2 holdout** (exact duplicates dropped before the split):",
        "",
        holdout_table(m),
        "",
        "**Before and after** (same model, same seed, same 80/20 stratified split):",
        "",
        comparison_table(m),
        "",
        f"On the original split, the {o['n_seen_in_train']} test messages that were also in train scored "
        f"{fmt(o['accuracy_seen_in_train'])}. The {o['n_unseen']} unseen ones scored {fmt(o['accuracy_unseen'])}.",
        "",
        f"Data: {a['rows']} rows, {a['unique_messages']} unique messages, {a['exact_duplicate_rows']} exact duplicate rows, "
        f"{a['label_conflicts']} label conflicts. Full audit in `results/audit.md`.",
        END,
    ])


def update_readme(m, path=README):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    pattern = re.compile(re.escape(START) + ".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise RuntimeError(f"{path} has no {START} ... {END} block")
    with open(path, "w", encoding="utf-8") as f:
        f.write(pattern.sub(lambda _: results_block(m), text))


def main(readme=README):
    audit = run_audit()
    metrics = run_evaluation(audit)
    if readme:
        update_readme(metrics, readme)
    print("Wrote results/audit.md, results/metrics.json, results/report.md, results/casebook.csv")
    if readme:
        print(f"Updated results table in {readme}")
    return metrics


if __name__ == "__main__":
    main()
